// Demo/seed data used so the UI has something rich to render before an org
// connects Supabase and completes onboarding. Never used for real accounts —
// gate all reads behind isSupabaseConfigured() checks upstream.

import type { Appointment, BusinessBrain, Contact, ConversationDetail, Message, Org } from "@/lib/types"

export const DEMO_ORG: Org = {
  id: "demo-org",
  name: "Sunrise Bakery",
  slug: "sunrise-bakery",
  created_at: "2026-01-01T00:00:00.000Z",
}

export const DEMO_BUSINESS_BRAIN: BusinessBrain = {
  org_id: DEMO_ORG.id,
  business_name: "Sunrise Bakery",
  category: "Bakery & Cafe",
  description:
    "A neighborhood bakery serving fresh sourdough, pastries, and coffee since 2019. Known for our cinnamon rolls and made-to-order birthday cakes.",
  hours: {
    monday: { open: "07:00", close: "18:00" },
    tuesday: { open: "07:00", close: "18:00" },
    wednesday: { open: "07:00", close: "18:00" },
    thursday: { open: "07:00", close: "18:00" },
    friday: { open: "07:00", close: "19:00" },
    saturday: { open: "08:00", close: "19:00" },
    sunday: { open: "08:00", close: "15:00" },
  },
  services: [
    {
      name: "Custom Birthday Cake",
      price: "$45",
      description: "Made-to-order, 48 hours notice.",
      duration_minutes: 60,
    },
    {
      name: "Cinnamon Roll (single)",
      price: "$4.50",
      description: "Our best seller, baked fresh every morning.",
    },
    {
      name: "Sourdough Loaf",
      price: "$8",
      description: "24-hour fermented, baked daily.",
    },
    {
      name: "Coffee Subscription",
      price: "$25/mo",
      description: "Weekly bag of house-roasted coffee.",
    },
    {
      name: "Catering Tray (dozen pastries)",
      price: "$60",
      description: "Mixed dozen, 24 hours notice.",
      duration_minutes: 30,
    },
    {
      name: "Kids Baking Class",
      price: "$35/child",
      description: "Saturdays 10am, ages 6-12, max 8 kids.",
      duration_minutes: 90,
    },
  ],
  prices: {
    "Custom Birthday Cake": "$45",
    "Cinnamon Roll (single)": "$4.50",
    "Sourdough Loaf": "$8",
    "Coffee Subscription": "$25/mo",
    "Catering Tray (dozen pastries)": "$60",
    "Kids Baking Class": "$35/child",
  },
  faq: [
    {
      question: "Do you take custom cake orders?",
      answer:
        "Yes! We need at least 48 hours notice for custom birthday cakes. Call or message us with your flavor and design ideas.",
    },
    {
      question: "Are you open on holidays?",
      answer:
        "We're closed on major holidays (New Year's Day, Thanksgiving, Christmas). Otherwise we're open our regular hours year-round.",
    },
    {
      question: "Do you have gluten-free or vegan options?",
      answer:
        "We offer a rotating gluten-free muffin and a vegan chocolate loaf daily, but our kitchen isn't allergen-free — please ask staff if you have a severe allergy.",
    },
    {
      question: "Can I place a large catering order?",
      answer:
        "Yes, catering trays serve 12+ and we ask for 24 hours notice. For orders over 5 trays, please give us a full week.",
    },
    {
      question: "Do you deliver?",
      answer:
        "We offer local delivery within 5 miles for orders over $30. Just mention delivery when you place your order.",
    },
  ],
  tone: "warm, friendly, a little playful — like a neighbor who happens to run the best bakery in town",
  brand_kit: {
    primary_color: "#6D5EF3",
    fonts: ["Inter", "Fraunces"],
    voice_keywords: ["cozy", "fresh-baked", "neighborhood", "handmade"],
  },
  connected_channels: {
    google_business: true,
    facebook: true,
    instagram: true,
    tiktok: false,
    sms: true,
    email: true,
    web_chat: true,
  },
  onboarding_step: 5,
  completed: true,
  updated_at: "2026-07-01T00:00:00.000Z",
}

// ---------------------------------------------------------------------------
// Unified Inbox + FrontDesk + CRM (Phase 2) demo data — mirrors
// supabase/migrations/0003_frontdesk.sql / src/lib/types.ts exactly (ids are
// stable strings so demo links like /contacts/demo-contact-1 stay stable).
// ---------------------------------------------------------------------------

/**
 * Demo-only shape used for DEMO_CONVERSATIONS: everything ConversationDetail
 * already carries (conversation + contact + messages), plus an optional
 * `pendingAiDraft`. `pendingAiDraft` is NOT part of the DB schema — per the
 * design brief, an "AI drafted — needs review" thread's draft text lives
 * only in the composer until sent, it's never a persisted message row. The
 * UI reads this field to pre-fill the composer for the one ai_state ===
 * "ai_draft" demo thread instead of calling the live model in demo mode.
 */
export type DemoConversationDetail = ConversationDetail & {
  pendingAiDraft?: string
}

export const DEMO_CONTACTS: Contact[] = [
  {
    id: "demo-contact-1",
    org_id: DEMO_ORG.id,
    name: "Emma Rodriguez",
    phone: "+1 (555) 010-1001",
    email: "emma.rodriguez@example.com",
    source: "web_chat",
    status: "lead",
    tags: ["birthday-cake"],
    notes: null,
    custom: {},
    created_at: "2026-07-14T15:02:00.000Z",
    updated_at: "2026-07-14T15:06:00.000Z",
  },
  {
    id: "demo-contact-2",
    org_id: DEMO_ORG.id,
    name: "Marcus Chen",
    phone: "+1 (555) 010-1002",
    email: null,
    source: "missed_call",
    status: "contacted",
    tags: ["follow-up", "subscription"],
    notes: "Missed our call on 7/13, followed up by text.",
    custom: {},
    created_at: "2026-07-13T18:41:00.000Z",
    updated_at: "2026-07-13T18:52:00.000Z",
  },
  {
    id: "demo-contact-3",
    org_id: DEMO_ORG.id,
    name: "Priya Patel",
    phone: "+1 (555) 010-1003",
    email: "priya.patel@example.com",
    source: "instagram",
    status: "lead",
    tags: ["catering", "vip"],
    notes: null,
    custom: {},
    created_at: "2026-07-15T20:10:00.000Z",
    updated_at: "2026-07-15T20:10:00.000Z",
  },
  {
    id: "demo-contact-4",
    org_id: DEMO_ORG.id,
    name: "Daniel Okafor",
    phone: null,
    email: "daniel.okafor@example.com",
    source: "email",
    status: "customer",
    tags: ["review", "regular"],
    notes: "Left a 5-star Google review 7/12.",
    custom: {},
    created_at: "2026-07-12T13:15:00.000Z",
    updated_at: "2026-07-12T13:24:00.000Z",
  },
  {
    id: "demo-contact-5",
    org_id: DEMO_ORG.id,
    name: "Sofia Alvarez",
    phone: "+1 (555) 010-1005",
    email: null,
    source: "facebook",
    status: "contacted",
    tags: [],
    notes: null,
    custom: {},
    created_at: "2026-07-11T09:30:00.000Z",
    updated_at: "2026-07-11T09:33:00.000Z",
  },
  {
    id: "demo-contact-6",
    org_id: DEMO_ORG.id,
    name: "James Whitfield",
    phone: "+1 (555) 010-1006",
    email: "james.whitfield@example.com",
    source: "google",
    status: "lead",
    tags: ["allergy"],
    notes: "Severe tree nut allergy for his daughter — confirm ingredients personally before replying.",
    custom: {},
    created_at: "2026-07-16T11:05:00.000Z",
    updated_at: "2026-07-16T11:05:00.000Z",
  },
  {
    id: "demo-contact-7",
    org_id: DEMO_ORG.id,
    name: "Grace Kim",
    phone: "+1 (555) 010-1007",
    email: "grace.kim@example.com",
    source: "web_chat",
    status: "booked",
    tags: ["kids-class"],
    notes: null,
    custom: {},
    created_at: "2026-07-10T16:20:00.000Z",
    updated_at: "2026-07-10T16:24:00.000Z",
  },
  {
    id: "demo-contact-8",
    org_id: DEMO_ORG.id,
    name: "Tyler Brooks",
    phone: "+1 (555) 010-1008",
    email: null,
    source: "sms",
    status: "booked",
    tags: ["reschedule"],
    notes: null,
    custom: {},
    created_at: "2026-07-09T08:00:00.000Z",
    updated_at: "2026-07-09T08:10:00.000Z",
  },
  {
    id: "demo-contact-9",
    org_id: DEMO_ORG.id,
    name: "Aisha Bello",
    phone: "+1 (555) 010-1009",
    email: "aisha.bello@example.com",
    source: "manual",
    status: "customer",
    tags: ["regular", "coffee-subscription"],
    notes: "Added manually after an in-store conversation.",
    custom: {},
    created_at: "2026-06-28T12:00:00.000Z",
    updated_at: "2026-06-28T12:00:00.000Z",
  },
  {
    id: "demo-contact-10",
    org_id: DEMO_ORG.id,
    name: "Noah Fitzgerald",
    phone: null,
    email: "noah.fitzgerald@example.com",
    source: "form",
    status: "lead",
    tags: ["catering"],
    notes: null,
    custom: {},
    created_at: "2026-07-08T17:45:00.000Z",
    updated_at: "2026-07-08T17:45:00.000Z",
  },
]

function demoMessage(input: {
  id: string
  conversationId: string
  direction: Message["direction"]
  kind?: Message["kind"]
  body: string
  aiHandled?: boolean
  model?: string | null
  costUsd?: number
  createdAt: string
}): Message {
  return {
    id: input.id,
    org_id: DEMO_ORG.id,
    conversation_id: input.conversationId,
    direction: input.direction,
    kind: input.kind ?? "message",
    body: input.body,
    ai_handled: input.aiHandled ?? false,
    model: input.model ?? null,
    cost_usd: input.costUsd ?? 0,
    metadata: {},
    created_at: input.createdAt,
  }
}

export const DEMO_CONVERSATIONS: DemoConversationDetail[] = [
  {
    id: "demo-conversation-1",
    org_id: DEMO_ORG.id,
    contact_id: "demo-contact-1",
    channel: "web_chat",
    status: "resolved",
    ai_state: "ai_answered",
    last_message_at: "2026-07-14T15:06:00.000Z",
    unread: false,
    created_at: "2026-07-14T15:02:00.000Z",
    updated_at: "2026-07-14T15:06:00.000Z",
    contact_name: "Emma Rodriguez",
    contact_phone: "+1 (555) 010-1001",
    contact_email: "emma.rodriguez@example.com",
    contact: DEMO_CONTACTS[0],
    messages: [
      demoMessage({
        id: "demo-message-1-1",
        conversationId: "demo-conversation-1",
        direction: "inbound",
        body: "Hi! Do you do custom birthday cakes? I need something for a 6th birthday party this Saturday \u{1F382}",
        createdAt: "2026-07-14T15:02:00.000Z",
      }),
      demoMessage({
        id: "demo-message-1-2",
        conversationId: "demo-conversation-1",
        direction: "outbound",
        body: "Yes we do! Our custom birthday cakes are $45 and we just need 48 hours notice. What flavor and any design ideas did you have in mind for the 6th birthday?",
        aiHandled: true,
        model: "anthropic/claude-haiku-4.5",
        costUsd: 0.0016,
        createdAt: "2026-07-14T15:03:00.000Z",
      }),
      demoMessage({
        id: "demo-message-1-3",
        conversationId: "demo-conversation-1",
        direction: "inbound",
        body: "Amazing! Chocolate with a dinosaur theme if possible",
        createdAt: "2026-07-14T15:05:00.000Z",
      }),
      demoMessage({
        id: "demo-message-1-4",
        conversationId: "demo-conversation-1",
        direction: "outbound",
        body: "Dinosaur chocolate cake sounds fun! We can definitely do that. I've got you down for pickup Saturday morning — I'll text you a confirmation once it's on the schedule. Anything else I can help with?",
        aiHandled: true,
        model: "anthropic/claude-haiku-4.5",
        costUsd: 0.0019,
        createdAt: "2026-07-14T15:06:00.000Z",
      }),
    ],
  },
  {
    id: "demo-conversation-2",
    org_id: DEMO_ORG.id,
    contact_id: "demo-contact-2",
    channel: "sms",
    status: "pending",
    ai_state: "ai_answered",
    last_message_at: "2026-07-13T18:52:00.000Z",
    unread: true,
    created_at: "2026-07-13T18:41:00.000Z",
    updated_at: "2026-07-13T18:52:00.000Z",
    contact_name: "Marcus Chen",
    contact_phone: "+1 (555) 010-1002",
    contact_email: null,
    contact: DEMO_CONTACTS[1],
    messages: [
      demoMessage({
        id: "demo-message-2-1",
        conversationId: "demo-conversation-2",
        direction: "outbound",
        body: "Hi! Sorry we missed your call at Sunrise Bakery \u{1F950} — how can we help? Reply here anytime.",
        aiHandled: true,
        model: "anthropic/claude-haiku-4.5",
        costUsd: 0.0011,
        createdAt: "2026-07-13T18:41:00.000Z",
      }),
      demoMessage({
        id: "demo-message-2-2",
        conversationId: "demo-conversation-2",
        direction: "inbound",
        body: "Hey, just wanted to check if you still have the coffee subscription available",
        createdAt: "2026-07-13T18:47:00.000Z",
      }),
      demoMessage({
        id: "demo-message-2-3",
        conversationId: "demo-conversation-2",
        direction: "outbound",
        body: "Yes! Our coffee subscription is $25/month for a weekly bag of house-roasted coffee. Want me to get you set up?",
        aiHandled: true,
        model: "anthropic/claude-haiku-4.5",
        costUsd: 0.0014,
        createdAt: "2026-07-13T18:50:00.000Z",
      }),
      demoMessage({
        id: "demo-message-2-4",
        conversationId: "demo-conversation-2",
        direction: "inbound",
        body: "Yes please, sign me up",
        createdAt: "2026-07-13T18:52:00.000Z",
      }),
    ],
  },
  {
    id: "demo-conversation-3",
    org_id: DEMO_ORG.id,
    contact_id: "demo-contact-3",
    channel: "instagram",
    status: "open",
    ai_state: "ai_draft",
    last_message_at: "2026-07-15T20:10:00.000Z",
    unread: true,
    created_at: "2026-07-15T20:10:00.000Z",
    updated_at: "2026-07-15T20:10:00.000Z",
    contact_name: "Priya Patel",
    contact_phone: "+1 (555) 010-1003",
    contact_email: "priya.patel@example.com",
    contact: DEMO_CONTACTS[2],
    messages: [
      demoMessage({
        id: "demo-message-3-1",
        conversationId: "demo-conversation-3",
        direction: "inbound",
        body: "Hi! I'm planning a corporate event for 40 people next month, do you do catering trays? What's the cost breakdown look like for that many people?",
        createdAt: "2026-07-15T20:10:00.000Z",
      }),
    ],
    pendingAiDraft:
      "Hi Priya! Yes, we'd love to help with your event. Our catering trays are $60 per dozen pastries — for 40 people we'd recommend about 4 trays (48 pastries), so roughly $240 total. We ask for at least a week's notice for orders over 5 trays, but 4 trays just needs 24 hours. Want me to pencil in a date?",
  },
  {
    id: "demo-conversation-4",
    org_id: DEMO_ORG.id,
    contact_id: "demo-contact-4",
    channel: "email",
    status: "resolved",
    ai_state: "human",
    last_message_at: "2026-07-12T13:24:00.000Z",
    unread: false,
    created_at: "2026-07-12T13:15:00.000Z",
    updated_at: "2026-07-12T13:24:00.000Z",
    contact_name: "Daniel Okafor",
    contact_phone: null,
    contact_email: "daniel.okafor@example.com",
    contact: DEMO_CONTACTS[3],
    messages: [
      demoMessage({
        id: "demo-message-4-1",
        conversationId: "demo-conversation-4",
        direction: "inbound",
        body: "Left you 5 stars on Google! The cinnamon rolls are seriously the best in town. Quick question — are you open on Labor Day?",
        createdAt: "2026-07-12T13:15:00.000Z",
      }),
      demoMessage({
        id: "demo-message-4-2",
        conversationId: "demo-conversation-4",
        direction: "outbound",
        body: "Thank you so much for the kind words, Daniel! We really appreciate it \u{1F64F} We are open on Labor Day with normal hours, hope to see you again soon!",
        createdAt: "2026-07-12T13:24:00.000Z",
      }),
    ],
  },
  {
    id: "demo-conversation-5",
    org_id: DEMO_ORG.id,
    contact_id: "demo-contact-5",
    channel: "facebook",
    status: "resolved",
    ai_state: "ai_answered",
    last_message_at: "2026-07-11T09:33:00.000Z",
    unread: false,
    created_at: "2026-07-11T09:30:00.000Z",
    updated_at: "2026-07-11T09:33:00.000Z",
    contact_name: "Sofia Alvarez",
    contact_phone: "+1 (555) 010-1005",
    contact_email: null,
    contact: DEMO_CONTACTS[4],
    messages: [
      demoMessage({
        id: "demo-message-5-1",
        conversationId: "demo-conversation-5",
        direction: "inbound",
        body: "What time do you guys open on Sundays?",
        createdAt: "2026-07-11T09:30:00.000Z",
      }),
      demoMessage({
        id: "demo-message-5-2",
        conversationId: "demo-conversation-5",
        direction: "outbound",
        body: "We're open 8am-3pm on Sundays! Come say hi \u{1F44B}",
        aiHandled: true,
        model: "anthropic/claude-haiku-4.5",
        costUsd: 0.0009,
        createdAt: "2026-07-11T09:33:00.000Z",
      }),
    ],
  },
  {
    id: "demo-conversation-6",
    org_id: DEMO_ORG.id,
    contact_id: "demo-contact-6",
    channel: "google",
    status: "pending",
    ai_state: "escalated",
    last_message_at: "2026-07-16T11:06:00.000Z",
    unread: true,
    created_at: "2026-07-16T11:05:00.000Z",
    updated_at: "2026-07-16T11:06:00.000Z",
    contact_name: "James Whitfield",
    contact_phone: "+1 (555) 010-1006",
    contact_email: "james.whitfield@example.com",
    contact: DEMO_CONTACTS[5],
    messages: [
      demoMessage({
        id: "demo-message-6-1",
        conversationId: "demo-conversation-6",
        direction: "inbound",
        body: "My daughter has a severe tree nut allergy. Can you guarantee the sourdough loaf is nut-free? Need to know before I order.",
        createdAt: "2026-07-16T11:05:00.000Z",
      }),
      demoMessage({
        id: "demo-message-6-2",
        conversationId: "demo-conversation-6",
        kind: "note",
        direction: "outbound",
        body: "I couldn't answer this — flagging for you. Severe allergy safety question, needs your confirmation on kitchen cross-contamination before we reply.",
        createdAt: "2026-07-16T11:06:00.000Z",
      }),
    ],
  },
  {
    id: "demo-conversation-7",
    org_id: DEMO_ORG.id,
    contact_id: "demo-contact-7",
    channel: "web_chat",
    status: "resolved",
    ai_state: "ai_answered",
    last_message_at: "2026-07-10T16:24:00.000Z",
    unread: false,
    created_at: "2026-07-10T16:20:00.000Z",
    updated_at: "2026-07-10T16:24:00.000Z",
    contact_name: "Grace Kim",
    contact_phone: "+1 (555) 010-1007",
    contact_email: "grace.kim@example.com",
    contact: DEMO_CONTACTS[6],
    messages: [
      demoMessage({
        id: "demo-message-7-1",
        conversationId: "demo-conversation-7",
        direction: "inbound",
        body: "Can I sign my 8 year old up for the Saturday baking class?",
        createdAt: "2026-07-10T16:20:00.000Z",
      }),
      demoMessage({
        id: "demo-message-7-2",
        conversationId: "demo-conversation-7",
        direction: "outbound",
        body: "Of course! The Kids Baking Class is $35/child, Saturdays at 10am for ages 6-12 (max 8 kids). I'll add your 8 year old to this Saturday's class — see you then!",
        aiHandled: true,
        model: "anthropic/claude-haiku-4.5",
        costUsd: 0.0017,
        createdAt: "2026-07-10T16:24:00.000Z",
      }),
    ],
  },
  {
    id: "demo-conversation-8",
    org_id: DEMO_ORG.id,
    contact_id: "demo-contact-8",
    channel: "sms",
    status: "resolved",
    ai_state: "human",
    last_message_at: "2026-07-09T08:10:00.000Z",
    unread: false,
    created_at: "2026-07-09T08:00:00.000Z",
    updated_at: "2026-07-09T08:10:00.000Z",
    contact_name: "Tyler Brooks",
    contact_phone: "+1 (555) 010-1008",
    contact_email: null,
    contact: DEMO_CONTACTS[7],
    messages: [
      demoMessage({
        id: "demo-message-8-1",
        conversationId: "demo-conversation-8",
        direction: "inbound",
        body: "Hey it's Tyler, I have a catering pickup scheduled for Friday but need to push it to Monday, is that possible?",
        createdAt: "2026-07-09T08:00:00.000Z",
      }),
      demoMessage({
        id: "demo-message-8-2",
        conversationId: "demo-conversation-8",
        direction: "outbound",
        body: "Hi Tyler, no problem — I've moved your catering pickup to Monday at the same time. See you then!",
        createdAt: "2026-07-09T08:10:00.000Z",
      }),
    ],
  },
]

export const DEMO_APPOINTMENTS: Appointment[] = [
  {
    id: "demo-appointment-1",
    org_id: DEMO_ORG.id,
    contact_id: "demo-contact-7",
    starts_at: "2026-07-18T17:00:00.000Z",
    ends_at: "2026-07-18T18:30:00.000Z",
    service: "Kids Baking Class",
    status: "scheduled",
    notes: "8 year old, first class.",
    created_at: "2026-07-10T16:24:00.000Z",
    updated_at: "2026-07-10T16:24:00.000Z",
  },
  {
    id: "demo-appointment-2",
    org_id: DEMO_ORG.id,
    contact_id: "demo-contact-1",
    starts_at: "2026-07-18T16:00:00.000Z",
    ends_at: "2026-07-18T16:15:00.000Z",
    service: "Custom Birthday Cake pickup",
    status: "scheduled",
    notes: "Chocolate, dinosaur theme.",
    created_at: "2026-07-14T15:06:00.000Z",
    updated_at: "2026-07-14T15:06:00.000Z",
  },
  {
    id: "demo-appointment-3",
    org_id: DEMO_ORG.id,
    contact_id: "demo-contact-8",
    starts_at: "2026-07-20T15:30:00.000Z",
    ends_at: "2026-07-20T15:45:00.000Z",
    service: "Catering Tray pickup",
    status: "scheduled",
    notes: "Rescheduled from Friday 7/17.",
    created_at: "2026-07-09T08:10:00.000Z",
    updated_at: "2026-07-09T08:10:00.000Z",
  },
]
