// GENERATED by scripts/vendor-theme-assets.ts — do not hand-edit.
// Re-run `npx tsx scripts/vendor-theme-assets.ts` to regenerate after
// changing the curated asset list in that script.
//
// Every entry here is a real vendored SVG file under this same directory
// (src/lib/templates/assets/<path>) — this module is a plain data import
// (no fs access), safe to import anywhere; src/lib/templates/themes.ts
// reads it at build/render time to resolve a theme key to concrete asset
// paths, and decorations.ts#stickerElement reads the actual SVG file at
// render time (see that module's header for why the read happens there
// instead of here).

export interface ThemeAssetManifestEntry {
  /** `${source}:${upstream icon name}` — stable identity for dedup/debugging, not used for lookups. */
  key: string
  /** Stable output name (matches the .svg filename, without extension). */
  name: string
  source: "noto" | "icon-park"
  license: string
  attribution: string
  /** Relative to src/lib/templates/assets/ — e.g. "christmas/christmas-tree.svg". */
  path: string
  /** Every occasion key this asset is available for (first = its primary/home occasion, where the file physically lives). */
  occasions: string[]
  note?: string
}

export const THEME_ASSET_MANIFEST: ThemeAssetManifestEntry[] = [
  {
    "key": "noto:christmas-tree",
    "name": "christmas-tree",
    "source": "noto",
    "license": "Apache-2.0",
    "attribution": "Noto Emoji, Google",
    "path": "christmas/christmas-tree.svg",
    "occasions": [
      "christmas"
    ]
  },
  {
    "key": "noto:santa-claus",
    "name": "santa-claus",
    "source": "noto",
    "license": "Apache-2.0",
    "attribution": "Noto Emoji, Google",
    "path": "christmas/santa-claus.svg",
    "occasions": [
      "christmas"
    ]
  },
  {
    "key": "noto:wrapped-gift",
    "name": "wrapped-gift",
    "source": "noto",
    "license": "Apache-2.0",
    "attribution": "Noto Emoji, Google",
    "path": "christmas/wrapped-gift.svg",
    "occasions": [
      "christmas",
      "birthday"
    ]
  },
  {
    "key": "noto:star",
    "name": "star",
    "source": "noto",
    "license": "Apache-2.0",
    "attribution": "Noto Emoji, Google",
    "path": "christmas/star.svg",
    "occasions": [
      "christmas"
    ]
  },
  {
    "key": "noto:snowman-without-snow",
    "name": "snowman-without-snow",
    "source": "noto",
    "license": "Apache-2.0",
    "attribution": "Noto Emoji, Google",
    "path": "christmas/snowman-without-snow.svg",
    "occasions": [
      "christmas"
    ]
  },
  {
    "key": "noto:party-popper",
    "name": "party-popper",
    "source": "noto",
    "license": "Apache-2.0",
    "attribution": "Noto Emoji, Google",
    "path": "new-year/party-popper.svg",
    "occasions": [
      "new-year",
      "birthday"
    ]
  },
  {
    "key": "noto:confetti-ball",
    "name": "confetti-ball",
    "source": "noto",
    "license": "Apache-2.0",
    "attribution": "Noto Emoji, Google",
    "path": "new-year/confetti-ball.svg",
    "occasions": [
      "new-year",
      "celebration-generic"
    ]
  },
  {
    "key": "noto:fireworks",
    "name": "fireworks",
    "source": "noto",
    "license": "Apache-2.0",
    "attribution": "Noto Emoji, Google",
    "path": "new-year/fireworks.svg",
    "occasions": [
      "new-year",
      "diwali"
    ]
  },
  {
    "key": "noto:sparkler",
    "name": "sparkler",
    "source": "noto",
    "license": "Apache-2.0",
    "attribution": "Noto Emoji, Google",
    "path": "new-year/sparkler.svg",
    "occasions": [
      "new-year"
    ]
  },
  {
    "key": "noto:clinking-glasses",
    "name": "clinking-glasses",
    "source": "noto",
    "license": "Apache-2.0",
    "attribution": "Noto Emoji, Google",
    "path": "new-year/clinking-glasses.svg",
    "occasions": [
      "new-year"
    ]
  },
  {
    "key": "noto:diya-lamp",
    "name": "diya-lamp",
    "source": "noto",
    "license": "Apache-2.0",
    "attribution": "Noto Emoji, Google",
    "path": "diwali/diya-lamp.svg",
    "occasions": [
      "diwali"
    ]
  },
  {
    "key": "noto:sparkles",
    "name": "sparkles",
    "source": "noto",
    "license": "Apache-2.0",
    "attribution": "Noto Emoji, Google",
    "path": "diwali/sparkles.svg",
    "occasions": [
      "diwali",
      "eid",
      "sale-generic",
      "celebration-generic"
    ]
  },
  {
    "key": "noto:jack-o-lantern",
    "name": "jack-o-lantern",
    "source": "noto",
    "license": "Apache-2.0",
    "attribution": "Noto Emoji, Google",
    "path": "halloween/jack-o-lantern.svg",
    "occasions": [
      "halloween"
    ]
  },
  {
    "key": "noto:ghost",
    "name": "ghost",
    "source": "noto",
    "license": "Apache-2.0",
    "attribution": "Noto Emoji, Google",
    "path": "halloween/ghost.svg",
    "occasions": [
      "halloween"
    ]
  },
  {
    "key": "noto:spider-web",
    "name": "spider-web",
    "source": "noto",
    "license": "Apache-2.0",
    "attribution": "Noto Emoji, Google",
    "path": "halloween/spider-web.svg",
    "occasions": [
      "halloween"
    ]
  },
  {
    "key": "noto:bat",
    "name": "bat",
    "source": "noto",
    "license": "Apache-2.0",
    "attribution": "Noto Emoji, Google",
    "path": "halloween/bat.svg",
    "occasions": [
      "halloween"
    ]
  },
  {
    "key": "noto:crescent-moon",
    "name": "crescent-moon",
    "source": "noto",
    "license": "Apache-2.0",
    "attribution": "Noto Emoji, Google",
    "path": "eid/crescent-moon.svg",
    "occasions": [
      "eid"
    ],
    "note": "Religious symbol — opt-in only. Never auto-applied by heuristics; only usable when the requester's copy explicitly names the occasion (e.g. \"Eid\")."
  },
  {
    "key": "noto:red-heart",
    "name": "red-heart",
    "source": "noto",
    "license": "Apache-2.0",
    "attribution": "Noto Emoji, Google",
    "path": "valentines/red-heart.svg",
    "occasions": [
      "valentines"
    ]
  },
  {
    "key": "noto:sparkling-heart",
    "name": "sparkling-heart",
    "source": "noto",
    "license": "Apache-2.0",
    "attribution": "Noto Emoji, Google",
    "path": "valentines/sparkling-heart.svg",
    "occasions": [
      "valentines"
    ]
  },
  {
    "key": "noto:rose",
    "name": "rose",
    "source": "noto",
    "license": "Apache-2.0",
    "attribution": "Noto Emoji, Google",
    "path": "valentines/rose.svg",
    "occasions": [
      "valentines"
    ]
  },
  {
    "key": "noto:birthday-cake",
    "name": "birthday-cake",
    "source": "noto",
    "license": "Apache-2.0",
    "attribution": "Noto Emoji, Google",
    "path": "birthday/birthday-cake.svg",
    "occasions": [
      "birthday"
    ]
  },
  {
    "key": "noto:balloon",
    "name": "balloon",
    "source": "noto",
    "license": "Apache-2.0",
    "attribution": "Noto Emoji, Google",
    "path": "birthday/balloon.svg",
    "occasions": [
      "birthday"
    ]
  },
  {
    "key": "icon-park:tag",
    "name": "tag",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "sale-generic/tag.svg",
    "occasions": [
      "sale-generic"
    ]
  },
  {
    "key": "noto:ribbon",
    "name": "ribbon",
    "source": "noto",
    "license": "Apache-2.0",
    "attribution": "Noto Emoji, Google",
    "path": "sale-generic/ribbon.svg",
    "occasions": [
      "sale-generic",
      "celebration-generic"
    ]
  }
]
