// GENERATED by scripts/vendor-theme-assets.ts — do not hand-edit.
// Re-run `npx tsx scripts/vendor-theme-assets.ts` to regenerate after
// changing the curated asset lists in that script.
//
// Every entry here is a real vendored SVG file under this same directory
// (src/lib/templates/assets/<path>) — this module is a plain data import
// (no fs access), safe to import anywhere. src/lib/templates/themes.ts
// resolves `occasions` entries (festival stickers); the Wave 4 element
// catalog (src/lib/ai/design-post.ts + src/lib/templates/elements.ts)
// resolves `topics` entries (semantic business-vertical icons).
// decorations.ts#stickerElement reads the actual SVG file at render
// time (see that module's header for why the read happens there instead
// of here).

export interface ThemeAssetManifestEntry {
  /** `${source}:${upstream icon name}` — stable identity for dedup/debugging, not used for lookups. */
  key: string
  /** Stable output name (matches the .svg filename, without extension). */
  name: string
  source: "icon-park" | "mingcute"
  license: string
  attribution: string
  /** Relative to src/lib/templates/assets/ — e.g. "christmas/christmas-tree.svg" or "topics/tech/terminal.svg". */
  path: string
  /** Every occasion (festival) key this asset is available for (first = its primary/home occasion), when applicable. */
  occasions?: string[]
  /** Every topic (business-vertical semantic) key this asset is available for (first = its primary/home topic), when applicable. */
  topics?: string[]
  note?: string
}

export const THEME_ASSET_MANIFEST: ThemeAssetManifestEntry[] = [
  {
    "key": "icon-park:christmas-tree",
    "name": "christmas-tree",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "christmas/christmas-tree.svg",
    "occasions": [
      "christmas"
    ]
  },
  {
    "key": "mingcute:snowman-line",
    "name": "snowman",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "christmas/snowman.svg",
    "occasions": [
      "christmas"
    ]
  },
  {
    "key": "mingcute:gift-line",
    "name": "gift",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "christmas/gift.svg",
    "occasions": [
      "christmas",
      "birthday"
    ]
  },
  {
    "key": "mingcute:star-line",
    "name": "star",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "christmas/star.svg",
    "occasions": [
      "christmas",
      "celebration-generic"
    ]
  },
  {
    "key": "mingcute:firework-line",
    "name": "firework",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "new-year/firework.svg",
    "occasions": [
      "new-year",
      "diwali"
    ]
  },
  {
    "key": "mingcute:wineglass-2-line",
    "name": "toast-glass",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "new-year/toast-glass.svg",
    "occasions": [
      "new-year"
    ]
  },
  {
    "key": "mingcute:candle-line",
    "name": "diya-lamp",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "diwali/diya-lamp.svg",
    "occasions": [
      "diwali"
    ]
  },
  {
    "key": "mingcute:sparkles-line",
    "name": "sparkles",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "diwali/sparkles.svg",
    "occasions": [
      "diwali",
      "eid",
      "sale-generic",
      "celebration-generic"
    ]
  },
  {
    "key": "mingcute:pumpkin-line",
    "name": "pumpkin",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "halloween/pumpkin.svg",
    "occasions": [
      "halloween"
    ]
  },
  {
    "key": "mingcute:ghost-line",
    "name": "ghost",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "halloween/ghost.svg",
    "occasions": [
      "halloween"
    ]
  },
  {
    "key": "icon-park:bat",
    "name": "bat",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "halloween/bat.svg",
    "occasions": [
      "halloween"
    ]
  },
  {
    "key": "mingcute:moon-line",
    "name": "crescent-moon",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "eid/crescent-moon.svg",
    "occasions": [
      "eid"
    ],
    "note": "Religious symbol — opt-in only. Never auto-applied by heuristics; only usable when the requester's copy explicitly names the occasion (e.g. \"Eid\")."
  },
  {
    "key": "mingcute:heart-line",
    "name": "heart",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "valentines/heart.svg",
    "occasions": [
      "valentines"
    ]
  },
  {
    "key": "mingcute:heart-hand-line",
    "name": "heart-gesture",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "valentines/heart-gesture.svg",
    "occasions": [
      "valentines"
    ]
  },
  {
    "key": "mingcute:rose-line",
    "name": "rose",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "valentines/rose.svg",
    "occasions": [
      "valentines"
    ]
  },
  {
    "key": "mingcute:cake-line",
    "name": "birthday-cake",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "birthday/birthday-cake.svg",
    "occasions": [
      "birthday"
    ]
  },
  {
    "key": "mingcute:balloon-2-line",
    "name": "balloon",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "birthday/balloon.svg",
    "occasions": [
      "birthday"
    ]
  },
  {
    "key": "icon-park:tag",
    "name": "tag",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "sale-generic/tag.svg",
    "occasions": [
      "sale-generic"
    ]
  },
  {
    "key": "mingcute:percentage-line",
    "name": "percent",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "sale-generic/percent.svg",
    "occasions": [
      "sale-generic"
    ]
  },
  {
    "key": "mingcute:terminal-line",
    "name": "terminal",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/tech/terminal.svg",
    "topics": [
      "tech"
    ]
  },
  {
    "key": "mingcute:group-line",
    "name": "team",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/tech/team.svg",
    "topics": [
      "tech"
    ]
  },
  {
    "key": "mingcute:cloud-line",
    "name": "cloud",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/tech/cloud.svg",
    "topics": [
      "tech"
    ]
  },
  {
    "key": "icon-park:data-server",
    "name": "server",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "topics/tech/server.svg",
    "topics": [
      "tech"
    ]
  },
  {
    "key": "mingcute:chip-line",
    "name": "chip",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/tech/chip.svg",
    "topics": [
      "tech"
    ]
  },
  {
    "key": "mingcute:monitor-line",
    "name": "monitor",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/tech/monitor.svg",
    "topics": [
      "tech"
    ]
  },
  {
    "key": "mingcute:mouse-line",
    "name": "computer-mouse",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/tech/computer-mouse.svg",
    "topics": [
      "tech"
    ]
  },
  {
    "key": "mingcute:wifi-line",
    "name": "wifi",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/tech/wifi.svg",
    "topics": [
      "tech"
    ]
  },
  {
    "key": "icon-park:printer",
    "name": "printer",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "topics/tech/printer.svg",
    "topics": [
      "tech"
    ]
  },
  {
    "key": "icon-park:browser",
    "name": "browser",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "topics/tech/browser.svg",
    "topics": [
      "tech"
    ]
  },
  {
    "key": "mingcute:bread-line",
    "name": "bread",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/food/bread.svg",
    "topics": [
      "food"
    ]
  },
  {
    "key": "mingcute:cake-line",
    "name": "cake-slice",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/food/cake-slice.svg",
    "topics": [
      "food"
    ]
  },
  {
    "key": "mingcute:table-line",
    "name": "dining-table",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/food/dining-table.svg",
    "topics": [
      "food"
    ]
  },
  {
    "key": "mingcute:truck-line",
    "name": "delivery-truck",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/food/delivery-truck.svg",
    "topics": [
      "food",
      "retail"
    ]
  },
  {
    "key": "icon-park:coffee-machine",
    "name": "coffee-machine",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "topics/food/coffee-machine.svg",
    "topics": [
      "food"
    ]
  },
  {
    "key": "icon-park:cocktail",
    "name": "cocktail",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "topics/food/cocktail.svg",
    "topics": [
      "food"
    ]
  },
  {
    "key": "mingcute:wine-line",
    "name": "wine",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/food/wine.svg",
    "topics": [
      "food"
    ]
  },
  {
    "key": "icon-park:teapot",
    "name": "teapot",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "topics/food/teapot.svg",
    "topics": [
      "food"
    ]
  },
  {
    "key": "icon-park:sandwich",
    "name": "sandwich",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "topics/food/sandwich.svg",
    "topics": [
      "food"
    ]
  },
  {
    "key": "mingcute:hamburger-line",
    "name": "burger",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/food/burger.svg",
    "topics": [
      "food"
    ]
  },
  {
    "key": "icon-park:comb",
    "name": "comb",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "topics/salon/comb.svg",
    "topics": [
      "salon"
    ]
  },
  {
    "key": "mingcute:mirror-line",
    "name": "mirror",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/salon/mirror.svg",
    "topics": [
      "salon"
    ]
  },
  {
    "key": "icon-park:nail-polish",
    "name": "nail-polish",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "topics/salon/nail-polish.svg",
    "topics": [
      "salon"
    ]
  },
  {
    "key": "mingcute:scissors-line",
    "name": "scissors-2",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/salon/scissors-2.svg",
    "topics": [
      "salon"
    ]
  },
  {
    "key": "mingcute:brush-line",
    "name": "hair-brush",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/salon/hair-brush.svg",
    "topics": [
      "salon"
    ]
  },
  {
    "key": "icon-park:spa-candle",
    "name": "spa-candle",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "topics/salon/spa-candle.svg",
    "topics": [
      "salon"
    ]
  },
  {
    "key": "icon-park:razor",
    "name": "razor",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "topics/salon/razor.svg",
    "topics": [
      "salon"
    ]
  },
  {
    "key": "icon-park:perfume",
    "name": "perfume",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "topics/salon/perfume.svg",
    "topics": [
      "salon"
    ]
  },
  {
    "key": "mingcute:lipstick-line",
    "name": "lipstick",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/salon/lipstick.svg",
    "topics": [
      "salon"
    ]
  },
  {
    "key": "mingcute:hammer-line",
    "name": "hammer",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/trades/hammer.svg",
    "topics": [
      "trades"
    ]
  },
  {
    "key": "icon-park:toolkit",
    "name": "toolbox",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "topics/trades/toolbox.svg",
    "topics": [
      "trades"
    ]
  },
  {
    "key": "mingcute:tool-line",
    "name": "tool",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/trades/tool.svg",
    "topics": [
      "trades"
    ]
  },
  {
    "key": "icon-park:electric-drill",
    "name": "drill",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "topics/trades/drill.svg",
    "topics": [
      "trades"
    ]
  },
  {
    "key": "mingcute:clipboard-line",
    "name": "clipboard",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/trades/clipboard.svg",
    "topics": [
      "trades"
    ]
  },
  {
    "key": "icon-park:ladder",
    "name": "ladder",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "topics/trades/ladder.svg",
    "topics": [
      "trades"
    ]
  },
  {
    "key": "mingcute:ruler-line",
    "name": "ruler",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/trades/ruler.svg",
    "topics": [
      "trades"
    ]
  },
  {
    "key": "icon-park:tape-measure",
    "name": "tape-measure",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "topics/trades/tape-measure.svg",
    "topics": [
      "trades"
    ]
  },
  {
    "key": "mingcute:percentage-line",
    "name": "percent-badge",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/retail/percent-badge.svg",
    "topics": [
      "retail"
    ]
  },
  {
    "key": "mingcute:shopping-bag-2-line",
    "name": "shopping-bag-2",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/retail/shopping-bag-2.svg",
    "topics": [
      "retail"
    ]
  },
  {
    "key": "icon-park:bill",
    "name": "receipt",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "topics/retail/receipt.svg",
    "topics": [
      "retail"
    ]
  },
  {
    "key": "mingcute:coupon-line",
    "name": "coupon",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/retail/coupon.svg",
    "topics": [
      "retail"
    ]
  },
  {
    "key": "mingcute:barcode-line",
    "name": "barcode",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/retail/barcode.svg",
    "topics": [
      "retail"
    ]
  },
  {
    "key": "mingcute:wallet-line",
    "name": "wallet",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/retail/wallet.svg",
    "topics": [
      "retail"
    ]
  },
  {
    "key": "mingcute:shopping-cart-1-line",
    "name": "shopping-cart",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/retail/shopping-cart.svg",
    "topics": [
      "retail"
    ]
  },
  {
    "key": "mingcute:gift-card-line",
    "name": "gift-card",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/retail/gift-card.svg",
    "topics": [
      "retail"
    ]
  },
  {
    "key": "icon-park:stamp",
    "name": "stamp",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "topics/retail/stamp.svg",
    "topics": [
      "retail"
    ]
  },
  {
    "key": "mingcute:run-line",
    "name": "running",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/fitness/running.svg",
    "topics": [
      "fitness"
    ]
  },
  {
    "key": "icon-park:heart-rate",
    "name": "heartbeat",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "topics/fitness/heartbeat.svg",
    "topics": [
      "fitness"
    ]
  },
  {
    "key": "mingcute:yoga-line",
    "name": "yoga",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/fitness/yoga.svg",
    "topics": [
      "fitness"
    ]
  },
  {
    "key": "mingcute:run-treadmill-line",
    "name": "treadmill",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/fitness/treadmill.svg",
    "topics": [
      "fitness"
    ]
  },
  {
    "key": "mingcute:medal-line",
    "name": "medal",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/fitness/medal.svg",
    "topics": [
      "fitness",
      "celebration"
    ]
  },
  {
    "key": "mingcute:award-line",
    "name": "award",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/fitness/award.svg",
    "topics": [
      "fitness"
    ]
  },
  {
    "key": "icon-park:stopwatch",
    "name": "stopwatch",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "topics/fitness/stopwatch.svg",
    "topics": [
      "fitness"
    ]
  },
  {
    "key": "mingcute:bottle-line",
    "name": "water-bottle",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/fitness/water-bottle.svg",
    "topics": [
      "fitness"
    ]
  },
  {
    "key": "mingcute:guitar-line",
    "name": "guitar",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/music-events/guitar.svg",
    "topics": [
      "music-events"
    ]
  },
  {
    "key": "mingcute:headphone-line",
    "name": "headphone",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/music-events/headphone.svg",
    "topics": [
      "music-events"
    ]
  },
  {
    "key": "icon-park:piano",
    "name": "piano",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "topics/music-events/piano.svg",
    "topics": [
      "music-events"
    ]
  },
  {
    "key": "mingcute:film-line",
    "name": "film",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/music-events/film.svg",
    "topics": [
      "music-events"
    ]
  },
  {
    "key": "mingcute:video-camera-line",
    "name": "video-camera",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/music-events/video-camera.svg",
    "topics": [
      "music-events"
    ]
  },
  {
    "key": "mingcute:mic-2-line",
    "name": "microphone-2",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/music-events/microphone-2.svg",
    "topics": [
      "music-events"
    ]
  },
  {
    "key": "icon-park:ticket-one",
    "name": "ticket-2",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "topics/music-events/ticket-2.svg",
    "topics": [
      "music-events"
    ]
  },
  {
    "key": "mingcute:drum-line",
    "name": "drum",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/music-events/drum.svg",
    "topics": [
      "music-events"
    ]
  },
  {
    "key": "icon-park:crown",
    "name": "crown",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "topics/music-events/crown.svg",
    "topics": [
      "music-events",
      "celebration"
    ]
  },
  {
    "key": "mingcute:balloon-2-line",
    "name": "balloon-2",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/celebration/balloon-2.svg",
    "topics": [
      "celebration"
    ]
  },
  {
    "key": "icon-park:gift-box",
    "name": "gift-box",
    "source": "icon-park",
    "license": "Apache-2.0",
    "attribution": "IconPark, ByteDance",
    "path": "topics/celebration/gift-box.svg",
    "topics": [
      "celebration"
    ]
  },
  {
    "key": "mingcute:sparkles-line",
    "name": "sparkle",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/celebration/sparkle.svg",
    "topics": [
      "celebration"
    ]
  },
  {
    "key": "mingcute:celebrate-line",
    "name": "celebrate",
    "source": "mingcute",
    "license": "Apache-2.0",
    "attribution": "MingCute Icon",
    "path": "topics/celebration/celebrate.svg",
    "topics": [
      "celebration"
    ]
  }
]
