// Theme layer (Wave 3) — maps a small, curated set of occasion/festival keys
// to (a) a palette hint that blends with the org's own brand colors, never
// replacing the brand's primary hue, and (b) a deterministic pick of 2-4
// vendored decorative assets (src/lib/templates/assets/, generated by
// scripts/vendor-theme-assets.ts) for template defs to place in their sticker
// slots (decorations.ts#stickerElement). Framework-free (no Satori/fs
// import) so it's cheap to reason about and test in isolation — the actual
// SVG file read happens in decorations.ts at render time.

import { THEME_ASSET_MANIFEST, type ThemeAssetManifestEntry } from "./assets/manifest"
import { darkenHex, lightenHex, mixHex, pickTextColor, relativeLuminance } from "./contrast"
import type { ColorRoles } from "./types"
import { hashSeed } from "./variants"

export type ThemeKey =
  | "christmas"
  | "new-year"
  | "diwali"
  | "halloween"
  | "eid"
  | "valentines"
  | "birthday"
  | "sale-generic"
  | "celebration-generic"

export interface ThemePaletteHint {
  /** A theme-associated accent hex — blended into `roles.accent` (see applyThemeToRoles). Never replaces the brand's own primary hue. */
  accentHex: string
  /** A theme-associated background hex — blended into `roles.backgroundStart`/`backgroundEnd`. */
  backgroundHex: string
  /** Human-readable summary shown nowhere in the UI yet — documents *why* these two hexes, for the next person tuning a theme. */
  description: string
}

export interface ThemeDef {
  key: ThemeKey
  label: string
  paletteHint: ThemePaletteHint
  /**
   * True for themes tied to a specific religion/culture (currently: eid —
   * see assets/manifest.ts's per-asset `note` on crescent-moon). These must
   * NEVER be auto-suggested by heuristics or "picked for variety" — only
   * ever applied when the requester's own words explicitly name the
   * occasion. src/lib/ai/design-post.ts's system prompt enforces this by
   * instruction; this flag exists so any future auto-suggestion feature
   * (e.g. a content-calendar "upcoming occasions" nudge) has a single place
   * to check before ever proposing this theme unprompted.
   */
  optInOnly?: boolean
}

// Palette hints: deep/moody background + one confident accent per occasion,
// chosen to read correctly across the vendored sticker art for that theme
// (e.g. Halloween's near-black background so a tinted pumpkin sticker's
// accent color actually pops) and to stay legible once contrast-checked in
// applyThemeToRoles below (pickTextColor re-derives every text-on-* role
// against the FINAL blended colors, not these raw hints).
export const THEMES: Record<ThemeKey, ThemeDef> = {
  christmas: {
    key: "christmas",
    label: "Christmas",
    paletteHint: { accentHex: "#C21F3A", backgroundHex: "#0B3B24", description: "deep pine green background, warm red accent" },
  },
  "new-year": {
    key: "new-year",
    label: "New Year",
    paletteHint: { accentHex: "#D4AF37", backgroundHex: "#0A0A1E", description: "midnight background, champagne-gold accent" },
  },
  diwali: {
    key: "diwali",
    label: "Diwali",
    paletteHint: { accentHex: "#E8A317", backgroundHex: "#3A0E1F", description: "deep maroon background, marigold-gold accent" },
  },
  halloween: {
    key: "halloween",
    label: "Halloween",
    paletteHint: { accentHex: "#FF7518", backgroundHex: "#0D0D0D", description: "near-black background, pumpkin-orange accent" },
  },
  eid: {
    key: "eid",
    label: "Eid",
    paletteHint: { accentHex: "#C9A24B", backgroundHex: "#0E3B30", description: "deep emerald background, soft gold accent" },
    optInOnly: true,
  },
  valentines: {
    key: "valentines",
    label: "Valentine's Day",
    paletteHint: { accentHex: "#E0457B", backgroundHex: "#3A0C1E", description: "deep rose background, warm pink accent" },
  },
  birthday: {
    key: "birthday",
    label: "Birthday",
    paletteHint: { accentHex: "#FF4FA3", backgroundHex: "#2C1B4D", description: "playful violet background, hot-pink accent" },
  },
  "sale-generic": {
    key: "sale-generic",
    label: "Sale / Promo",
    paletteHint: { accentHex: "#E23B3B", backgroundHex: "#161616", description: "near-black background, urgent red accent" },
  },
  "celebration-generic": {
    key: "celebration-generic",
    label: "Celebration",
    paletteHint: { accentHex: "#7C5CFF", backgroundHex: "#171226", description: "deep violet background, bright accent" },
  },
}

export const THEME_KEYS = Object.keys(THEMES) as ThemeKey[]

export function isThemeKey(value: string): value is ThemeKey {
  return Object.prototype.hasOwnProperty.call(THEMES, value)
}

/** Looks up a theme by key. Returns null (never throws) for an unknown key — callers (render.ts, design-post.ts) treat that exactly like "no theme". */
export function getTheme(key: string): ThemeDef | null {
  return isThemeKey(key) ? THEMES[key] : null
}

// ===========================================================================
// Palette blending — brand primary always wins; theme only nudges accent +
// background.
// ===========================================================================

/** How strongly a theme's palette hint pulls the resolved accent/background away from the brand's own colors, 0-1. Deliberately theme-dominant (0.6) — an org applying "Christmas" wants the poster to unmistakably read as Christmas, with the brand's own hue still present underneath via the mix rather than fully replaced. */
const THEME_BLEND_STRENGTH = 0.6

/**
 * Blends a theme's palette hint into resolved color roles. `roles.primary`
 * is NEVER touched (brand identity always stays) — only `accent`,
 * `backgroundStart`, and `backgroundEnd` are nudged via
 * contrast.ts#mixHex, then every `textOn*` role is re-derived from the
 * FINAL blended colors via contrast.ts#pickTextColor so text stays WCAG
 * AA-safe. Returns `roles` unchanged when `themeKey` is null/undefined/
 * unknown.
 */
export function applyThemeToRoles(roles: ColorRoles, themeKey: string | null | undefined): ColorRoles {
  const theme = themeKey ? getTheme(themeKey) : null
  if (!theme) return roles

  const accent = mixHex(roles.accent, theme.paletteHint.accentHex, THEME_BLEND_STRENGTH)

  // Derive a start/end pair from the theme's single background hex that
  // preserves the SAME lighter->darker (or darker->lighter) relationship the
  // original roles already had, so the gradient direction never flips.
  const startIsDarkerThanEnd = relativeLuminance(roles.backgroundStart) < relativeLuminance(roles.backgroundEnd)
  const themeStartHex = startIsDarkerThanEnd ? lightenHex(theme.paletteHint.backgroundHex, 0.06) : darkenHex(theme.paletteHint.backgroundHex, 0.06)
  const themeEndHex = startIsDarkerThanEnd ? darkenHex(theme.paletteHint.backgroundHex, 0.12) : lightenHex(theme.paletteHint.backgroundHex, 0.12)

  const backgroundStart = mixHex(roles.backgroundStart, themeStartHex, THEME_BLEND_STRENGTH)
  const backgroundEnd = mixHex(roles.backgroundEnd, themeEndHex, THEME_BLEND_STRENGTH)

  return {
    primary: roles.primary,
    accent,
    backgroundStart,
    backgroundEnd,
    textOnLight: pickTextColor(backgroundStart),
    textOnDark: pickTextColor(backgroundEnd),
    textOnAccent: pickTextColor(accent),
    isDarkBackground: roles.isDarkBackground,
  }
}

// ===========================================================================
// Asset resolution — deterministic-from-seed pick of 2-4 assets for one
// occasion.
// ===========================================================================

export interface ResolvedThemeAsset {
  /** Relative to src/lib/templates/assets/ — e.g. "christmas/christmas-tree.svg". Pass straight to decorations.ts#stickerElement. */
  path: string
  /** Stable short name (matches the manifest entry's `name`) — useful for a per-sticker-unique jitter seed (decorations.ts#stickerRotationJitter). */
  name: string
  source: ThemeAssetManifestEntry["source"]
}

const MIN_THEME_ASSETS = 2
const MAX_THEME_ASSETS = 4

/**
 * Deterministically picks 2-4 assets for `themeKey` from the vendored
 * manifest (src/lib/templates/assets/manifest.ts), stably ranked by
 * `${seed}:${asset key}` so the SAME seed always returns the SAME
 * subset+order (a template rendering twice with the same seed must be
 * byte-identical, per render.ts's contract), while different seeds spread
 * across the full pool. Returns `[]` for an unknown theme key or a theme
 * with no manifest entries — callers (template defs) must treat that as
 * "render with no stickers," never as an error.
 */
export function resolveThemeAssets(themeKey: string, seed: string, count = 3): ResolvedThemeAsset[] {
  if (!isThemeKey(themeKey)) return []
  const pool = THEME_ASSET_MANIFEST.filter((entry) => entry.occasions?.includes(themeKey))
  if (pool.length === 0) return []

  const wanted = Math.max(MIN_THEME_ASSETS, Math.min(count, MAX_THEME_ASSETS, pool.length))
  const ranked = pool
    .map((entry) => ({ entry, rank: hashSeed(`${seed}:${entry.key}`) }))
    .sort((a, b) => a.rank - b.rank)
    .slice(0, wanted)

  return ranked.map(({ entry }) => ({ path: entry.path, name: entry.name, source: entry.source }))
}

// ===========================================================================
// Tier 3 (documented seam, NOT wired this wave)
// ===========================================================================

/**
 * Tier 3 of the license-approved asset architecture: long-tail themes
 * beyond the curated Tier-1 vendored set above (occasions with no good
 * IconPark/MingCute match) would be generated ONCE via Recraft (fal.ai,
 * vector-style output suits sticker use) and cached in Supabase Storage —
 * mirroring src/lib/media/slideshow.ts's "generate once, reuse forever"
 * asset-caching discipline rather than paying a generation cost on every
 * render. This function is the seam a future wave wires up: it intentionally
 * always returns null today (Tier 1's resolveThemeAssets above is the only
 * live path), so every caller must already treat a null/empty resolution as
 * "render without that sticker" — which they do, by construction.
 */
export function resolveGeneratedElement(themeKey: string): ResolvedThemeAsset | null {
  void themeKey
  return null
}
